// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sign_up_api.DbContexts;

#nullable disable

namespace sign_up_api.Migrations
{
    [DbContext(typeof(SignUpDbContext))]
    partial class SignUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("sign_up_api.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("sign_up_api.Entities.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Industries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eac151a3-4f75-4f5a-bd74-324196cdb406"),
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = new Guid("a81e933c-c75c-4cf2-bd88-12f802d1f6e0"),
                            Name = "Finance and Banking"
                        },
                        new
                        {
                            Id = new Guid("dd684a75-8015-4d48-908c-bad475c96568"),
                            Name = "Retail and E-commerce"
                        },
                        new
                        {
                            Id = new Guid("af0ab3be-f51d-43fa-84e2-358eaa6adb9e"),
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = new Guid("5ce89290-6ba9-4263-a8d6-1549de9fc6a3"),
                            Name = "Telecommunications"
                        });
                });

            modelBuilder.Entity("sign_up_api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("sign_up_api.Entities.Company", b =>
                {
                    b.HasOne("sign_up_api.Entities.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("sign_up_api.Entities.Industry", b =>
                {
                    b.HasOne("sign_up_api.Entities.Company", null)
                        .WithMany("Industries")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("sign_up_api.Entities.User", b =>
                {
                    b.HasOne("sign_up_api.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("sign_up_api.Entities.Company", b =>
                {
                    b.Navigation("Industries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("sign_up_api.Entities.Industry", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
